language: java
#sudo: false # faster builds
dist: trusty

jdk:
    - oraclejdk8

install:
  - pip install --user codecov
    
script:
  -- mvn -DskipTests=true clean package
  -- mvn cobertura:cobertura"


after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2
    - $HOME/.jdk
    - $HOME/.cache/pip