language: java
#sudo: false # faster builds
dist: trusty

jdk:
    - oraclejdk8

script:
    mvn -DskipTests=true clean package


install:
  - pip install --user codecov


after_success:
  # codecov
  - codecov