language: java
#sudo: false # faster builds
dist: trusty

jdk:
    - oraclejdk11

env:
  - GRAALVM_VERSION="20.0.0"
#  - CODECOV_TOKEN="500df02a-c889-4aea-8d2a-8b8ac0d5b964"

install:
  - pip install --user codecov

script:
  - LOG=/app/docker
  # - mvn -DskipTests=true clean package
  # - mvn test > ${LOG}/testLog 2>&1
  #  - mvn test
  #  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2
    - $HOME/.jdk
    - $HOME/.cache/pip
