language: java
#sudo: false # faster builds
dist: trusty

jdk:
    - oraclejdk11

env:
#  - GRAALVM_VERSION="20.0.0"
#  - CODECOV_TOKEN="6267e9fd-fc9a-411a-be60-07e8d07b6697"

#install:
#  - pip install --user codecov
install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -Dmaven.test.skip=true

script:
#  "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true"
#    - LOG=/app/docker
#    - mvn -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true clean package
#    - mvn test > ${LOG}/testLog 2>&1
#    - mvn test
#    - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2
    - $HOME/.jdk
#    - $HOME/.cache/pip
