language: java
#sudo: false # faster builds
dist: trusty

jdk:
    - oraclejdk8

install:
  - pip install --user codecov
    
script:
    mvn -DskipTests=true clean package


after_success:
  - jdk_switcher use oraclejdk8
  - codecov